name: Java CI with Maven in Linux
on:
  push: 
  pull_request: 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: ToDoApplicationMultiDB
    strategy:
      matrix:
        include:
        - java: 11
             
    name: Build with Java ${{ matrix.java }} on Linux
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml','**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Unit and Integration Tests
      run: mvn verify -Pjacoco
      working-directory: ${{env.workdir}}
      
    - name: Coveralls Report
      run: >
        mvn coveralls:report
        -DrepoToken=$COVERALLS_REPO_TOKEN
        -DpullRequest=${{ github.event.pull_request.number }}
      working-directory: ${{env.workdir}}
      env: 
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    - name: End-to-end tests
      run: xvfb-run mvn verify -Pe2e-tests
      working-directory: ${{env.workdir}}
    - name: SonarCloud
      run: >
        mvn sonar:sonar
        -Dsonar.projectKey=BernabeiPietro_todomultidb
      working-directory: ${{env.workdir}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
